version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: daily
    ignore:
      - dependency-name: org.slf4j:slf4j-simple
        update-types: ["version-update:semver-major"] # tc is on 1.7.x
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
