name: Submit Dependencies

on:
  push:
    branches: ['main']

permissions:
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
    - name: Set up JDK 17
      uses: actions/setup-java@6a0805fcefea3d4657a47ac4c165951e33482018
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@16bf8bc8fe830fa669c3c9f914d3eb147c629707
